# Generated by Django 2.2 on 2020-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='Old Book', max_length=255),
            preserve_default=False,
        ),
    ]
